@Library('SharedLib') _

pipeline {
    agent any

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: 'trainwithshubham/wanderlust-frontend-beta:v2.2', description: 'Frontend Docker tag')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: 'trainwithshubham/wanderlust-backend-beta:v2.1', description: 'Backend Docker tag')
    }

    stages {
        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("https://github.com/TDevendra532/Wanderlust-Mega-Project.git", "main")
                }
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "Using Shubham's Docker Images:"
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            sed -i -e 's|image: .*trainwithshubham/wanderlust-backend-beta:.*|image: ${params.BACKEND_DOCKER_TAG}|' backend.yaml
                        """
                        sh """
                            sed -i -e 's|image: .*trainwithshubham/wanderlust-frontend-beta:.*|image: ${params.FRONTEND_DOCKER_TAG}|' frontend.yaml
                        """
                    }
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                        git config --global user.email "devendratalhande726@gmail.com"
                        git config --global user.name "TDevendra532"

                        echo "Checking repository status:"
                        git status

                        echo "Adding changes to git:"
                        git add .

                        echo "Committing changes:"
                        git commit -m "Updated Kubernetes manifests with latest image tags"

                        echo "Pushing changes to GitHub:"
                        git push https://github.com/TDevendra532/Wanderlust-Mega-Project.git main
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                emailext attachLog: true,
                from: 'devendratalhande726@gmail.com',
                subject: "Wanderlust Application Updated & Deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <p><strong>Project:</strong> ${env.JOB_NAME}</p>
                        <p><strong>Build Number:</strong> ${env.BUILD_NUMBER}</p>
                        <p><strong>URL:</strong> ${env.BUILD_URL}</p>
                    </body>
                    </html>
                """,
                to: 'devendratalhande726@gmail.com',
                mimeType: 'text/html'
            }
        }
        failure {
            script {
                emailext attachLog: true,
                from: 'devendratalhande726@gmail.com',
                subject: "Wanderlust Application Build Failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <p><strong>Project:</strong> ${env.JOB_NAME}</p>
                        <p><strong>Build Number:</strong> ${env.BUILD_NUMBER}</p>
                    </body>
                    </html>
                """,
                to: 'devendratalhande726@gmail.com',
                mimeType: 'text/html'
            }
        }
    }
}
